---
- name: create users Alice, Bob, Carol
  hosts: nodes
  vars_files:
    - vars/users 

  tasks:
  - name: create users
    user:
      name: "{{ item.key }}"
      comment: "{{ item.value.email }}"
      home: "{{ item.value.homedir }}"
      password: "{{ item.value.password }}"
      update_password: on_create
      state: present
    with_dict: "{{ users }}"

