---
- name: uninstall Apache web server
  hosts: nodes

  tasks:
  - name: remove httpd
    package:
      name: httpd
      state: absent
  - name: file index.html deletion
    file:
      path: /var/www/html/index.html
      state: absent
  - name: configure firewalld
    firewalld:
      immediate: yes
      permanent: yes
      service: http
      state: disabled

